// <auto-generated />
namespace PBManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmanyusersroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmanyusersroles));
        
        string IMigrationMetadata.Id
        {
            get { return "202008161429135_add-many-users-roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
