// <auto-generated />
namespace PBManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init481 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init481));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051027108_init481"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
