// <auto-generated />
namespace PBManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class accountdeleteoncascadecashflow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(accountdeleteoncascadecashflow));
        
        string IMigrationMetadata.Id
        {
            get { return "202101021153566_account-deleteoncascade-cashflow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
